services:
  - type: web
    name: backend
    runtime: node
    plan: free
    branch: main
    autoDeployTrigger: commit
    rootDir: games/star-sprint
    buildFilter:
      paths:
        - render.yaml
        - games/star-sprint/**
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
